env: dev
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    druid:
      url: jdbc:sqlserver://192.168.0.150:1433;DatabaseName=mytest
      username: sa
      password: root
